Add vprintf support
NessieCircuits/Riotee_SDK pull request #18
Opened 2024-01-23 07:06 UTC by rydeom

Its nothing special, but its nice so have (I needed it lol)

2024-02-01 22:51 UTC, geissdoerfer requested changes
Please remove the newer two commits from this PR -  they are not related to the vprintf support. I will merge the no-cap-mon branch now, so this functionality becomes available. Finally, please create a separate PR for the missing label and explain in the comments, why this is needed. Thanks!

2024-02-01 22:51 UTC, geissdoerfer commented on core/include/printf.h
Please don't change the formatting of this file. It's an external library and I would like to be able to diff it with a new version.

2024-02-01 22:51 UTC, geissdoerfer commented on core/runtime.c
Are these just the changes that are already on the no-cap-mon branch? In that case, I would just merge them from there.

2024-02-01 22:51 UTC, geissdoerfer commented on linker.ld
> +                end = __bss_end__;
Where is this label needed? Why is there no _start_ label, but just an end label?

2024-02-02 01:46 UTC, rydeom commented
Sorry for the messed up stuff. Now its only the important changes.

2024-02-02 02:10 UTC, geissdoerfer approved these changes

2024-02-02 02:12 UTC, merged